modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="fate_tokens"
version="0.1.0"
displayName="Fate Tokens"
displayURL="https://github.com/openfinch/fate_tokens"
credits="Created by HiddenDip, using MCreator"
authors="hiddendip"
description="Allows players to resurrect each other in Hardcore using Fate Tokens. Based on Minecraft S.O.S."

[[dependencies.fate_tokens]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




