name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

env:
  JAVA_VERSION: 17

jobs:
  build:
    name: Minecraft ${{matrix.minecraft_version}} / Forge ${{matrix.forge_version}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { minecraft_version: "1.20.1", forge_version: "47.2.0" }
    runs-on: ubuntu-latest      
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: FORGE_VERSION="net.minecraftforge:forge:${{matrix.minecraft_version}}-${{matrix.forge_version}}" ./gradlew clean build

      - name: Upload build artifact
        uses: "actions/upload-artifact@v4"
        with:
          name: fate_tokens-${{matrix.minecraft_version}}-${{matrix.forge_version}}
          path: "build/libs/*"